# 数据库配置
database:
  host: "localhost"  # 数据库主机
  port: 3306         # 数据库端口
  user: "root"       # 数据库用户名
  password: "123456"  # 数据库密码
  dbname: "app"  # 数据库名称

# Redis配置
redis:
  host: "localhost"  # Redis主机
  port: 6379         # Redis端口

# JWT配置
jwt:
  secret: "your-secret-key"  # JWT密钥
  expire: 3600  # JWT过期时间（秒）

# 服务器配置
server:
  port: 8080  # 服务器端口
  mode: "debug"  # 运行模式：debug或release

# 短信服务配置
sms:
  provider: "aliyun"  # 短信服务提供商，目前支持aliyun
  aliyun:
    access_key_id: "your-access-key-id"       # 阿里云AccessKey ID
    access_key_secret: "your-access-key-secret" # 阿里云AccessKey Secret
    region_id: "cn-hangzhou"                   # 地域ID
    sign_name: "your-sign-name"                # 短信签名
    template_code: "SMS_315625116"             # 短信模板ID

# 日志配置
logger:
  level: "info"           # 日志级别: debug, info, warn, error, fatal
  file_path: "./logs/app.log"  # 日志文件路径
  max_size: 100           # 单个日志文件最大大小，单位MB
  max_backups: 10         # 最大保留的旧日志文件数量
  max_age: 30             # 保留日志文件的最大天数
  compress: true          # 是否压缩旧日志文件
  console: true           # 是否同时输出到控制台
